align bootstrap-localhost with bootstrap-system; corrected new npm use; clean-up node_modules on re-run.

diff --git a/bootstrap-system b/bootstrap-system
--- a/bootstrap-system
+++ b/bootstrap-system
@@ -10,8 +10,6 @@ CONF=${DIR}/host.json
 
 ./bootstrap/prepare
 ./bootstrap/node
-# Executables
-(cd && sudo npm -g install coffee-script)
 
 HOSTNAME=`hostname`
 
@@ -53,6 +51,9 @@ else
 JSON
 fi
 
+# Cleanup any previous run
+(cd && rm -rf node_modules)
+
 (cd && npm install "${SRC}/"applications/_users)
 (cd && npm run-script ccnq3_users security)
 
@@ -64,8 +65,8 @@ fi
 (cd && npm run-script ccnq3_host couchapps)
 (cd && npm run-script ccnq3_host bootstrap)
 
-ccnq3_host stop || echo
-ccnq3_host start
+npm stop  ccnq3_host || echo
+npm start ccnq3_host
 
 echo
 echo "To manage your system, please access ${CDB_URI}/provisioning/_design/app/index.html or a suitable redirection."
